# Generated by Django 4.0.5 on 2022-06-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='company',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
