# Generated by Django 4.0.5 on 2022-06-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sponsor_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='phone_number',
            field=models.IntegerField(default='+998993362767'),
            preserve_default=False,
        ),
    ]
